version: "3.8"

services:
  # Image Optimizer Service
  image-optimizer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: image-optimizer
    ports:
      - "3101:3000"
    environment:
      - PORT=3000
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - R2_ACCOUNT_ID=$R2_ACCOUNT_ID
      - R2_ACCESS_KEY_ID=$R2_ACCESS_KEY_ID
      - R2_SECRET_ACCESS_KEY=$R2_SECRET_ACCESS_KEY
      - R2_BUCKET_NAME=$R2_BUCKET_NAME
      - R2_REGION=$R2_REGION
    restart: unless-stopped
    volumes:
      # Mount logs directory to persist logs
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000/health"]
      interval: 5s
      timeout: 20s
      retries: 10
